// web/src/js/App.svelte
<script>
import { onMount } from 'svelte';

let loadingListeners = false;
let listeners = [];

onMount(() => {
  loadingListeners = true;
  fetch('/listeners')
    .then((response) => response.json())
    .then((newListeners) => {
      loadingListeners = false;
      listeners = Object.values(newListeners);
    });
});
</script>

{#if loadingListeners}
  <p>Loading...</p>
{:else}
  <h2>Listeners</h2>
  <ul>
  {#each listeners as listener}
    <li>{listener.configuration.port}: {listener.enabledUpstreams.join(',')}</li>
  {/each}
  </ul>
{/if}

// web/src/js/components/App.vue
<template>
  <div v-if="loadingListeners">Loading...</div>  
  <div v-else>
    <h2>Listeners</h2>
    <ul>
      <li v-for="listener in listeners" v-bind:key="listener.configuration.port">
        {{ listener.configuration.port }}: {{ listener.enabledUpstreams }}
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  created() {
    this.loadListeners();
  },

  data() {
    return {
      loadingListeners: false,
      listeners: [],
    }
  },

  methods: {
    loadListeners: function () {
      this.loadingListeners = true;
      fetch('/listeners')
        .then((response) => response.json())
        .then((listeners) => {
          this.listeners = Object.values(listeners);
          this.loadingListeners = false;
        });
    }
  },
}
</script>
